name: Verificación de Versión y Pruebas CI

on:
  push:
    tags:
      - 'v*'  # Se activa al publicar cualquier tag que comience con 'v'

jobs:
  verify-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validar ejecución del módulo de asistencia
        run: |
          python main.py